In [2]:
from pathlib import Path
base_dir = Path("/hpcwork/fw641779/lbm/Toray-120C")

In [4]:
from lbm_wetting.utils.structure_prep import read_vti_file

# Read vti file
data = read_vti_file(base_dir / "55cov/structure0/structure.vti")
structure = data["structure"]
print(structure)

[[[  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  ...
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]]

 [[  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  ...
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]]

 [[  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  ...
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]]

 ...

 [[  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  ...
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]]

 [[  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  ...
  [  0   0   0 ...   0   0 255]
  [  0   0   0 ...   0   0 255]
  [  0   0   0 ...   0   0 2

In [4]:
# Crop structure to 50x50x50
structure = structure[250:300, 250:300, 150:200]

# Save cropped structure
np.save(base_dir / "structure_cropped.npy", structure)